package com.plcoding.contactscomposemultiplatform.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color


val LightPrimary = Color(0xFFBF0031)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDAD9)
val LightOnPrimaryContainer = Color(0xFF40000A)
val LightSecondary = Color(0xFF775656)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDAD9)
val LightOnSecondaryContainer = Color(0xFF2C1516)
val LightTertiary = Color(0xFF755A2F)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDDAF)
val LightOnTertiaryContainer = Color(0xFF281800)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF201A1A)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF201A1A)
val LightSurfaceVariant = Color(0xFFF4DDDD)
val LightOnSurfaceVariant = Color(0xFF524343)
val LightOutline = Color(0xFF857373)
val LightInverseOnSurface = Color(0xFFFBEEED)
val LightInverseSurface = Color(0xFF362F2F)
val LightInversePrimary = Color(0xFFFFB3B4)
val LightSurfaceTint = Color(0xFFBF0031)

val DarkPrimary = Color(0xFFFFB3B4)
val DarkOnPrimary = Color(0xFF680016)
val DarkPrimaryContainer = Color(0xFF920023)
val DarkOnPrimaryContainer = Color(0xFFFFDAD9)
val DarkSecondary = Color(0xFFE6BDBC)
val DarkOnSecondary = Color(0xFF44292A)
val DarkSecondaryContainer = Color(0xFF5D3F3F)
val DarkOnSecondaryContainer = Color(0xFFFFDAD9)
val DarkTertiary = Color(0xFFE5C18D)
val DarkOnTertiary = Color(0xFF422C05)
val DarkTertiaryContainer = Color(0xFF5B421A)
val DarkOnTertiaryContainer = Color(0xFFFFDDAF)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF201A1A)
val DarkOnBackground = Color(0xFFECE0DF)
val DarkSurface = Color(0xFF201A1A)
val DarkOnSurface = Color(0xFFECE0DF)
val DarkSurfaceVariant = Color(0xFF524343)
val DarkOnSurfaceVariant = Color(0xFFD7C1C1)
val DarkOutline = Color(0xFFA08C8C)
val DarkInverseOnSurface = Color(0xFF201A1A)
val DarkInverseSurface = Color(0xFFECE0DF)
val DarkInversePrimary = Color(0xFFBF0031)
val DarkSurfaceTint = Color(0xFFFFB3B4)
